"""
WebPres project v1.
Generated by 'django-admin startproject' using Django 3.2.9.
By ronyman.com
"""


from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from apps.hello_world.admin import admin_site


urlpatterns = [
    # Core_urls
    #path('wp_admin/', wp_admin_site.site.urls),
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('blog.urls')),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
